reporting:
  dir: ./reports/coverage
instrumentation:
  default-excludes: true
  excludes: [ "config/**", "server.js" ]
check:
  global:
    statements: 90
    lines: 90
    branches: 80
    functions: 90
  each:
    statements: 75
    lines: 75
    branches: 50
    functions: 75
